# Top-level configuration
name = "fretgreen"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2022-07-12"

[[d1_databases]]
binding = "fretgreen-app"
database_name = "fretgreen-app"
database_id = "5773b453-5c38-4440-9c8b-7d81c7705bce"
migrations_dir = "./server/database/migrations"

[vars]
NUXT_BASE_URL = "http://localhost:3000"

[env.production.vars]
NUXT_BASE_URL = "https://fretgreen.bureaudefret.com"